TYPES: BEGIN OF TY_EMPLOYEE,
         EMP_ID     TYPE ZEMPLOYEE_ID_DATA_ELEMENT_8_10,
         EMP_NAME   TYPE ZEMPLOYEE_NAME_DE_8_10,
         DEPARTMENT TYPE ZDEPARTMENT_DE_8_10,
         MANAGER    TYPE ZMANAGER_DE_8_10,
       END OF TY_EMPLOYEE.

DATA LT_EMPLOYEE TYPE TABLE OF TY_EMPLOYEE.

DATA LS_EMPLOYEE TYPE TY_EMPLOYEE.

LS_EMPLOYEE-EMP_ID = '101'.
LS_EMPLOYEE-EMP_NAME = ' SAIKRISHNA'.
LS_EMPLOYEE-DEPARTMENT = 'SAP ABAP'.
LS_EMPLOYEE-MANAGER = 'KRISHNA'.
APPEND LS_EMPLOYEE TO LT_EMPLOYEE.
CLEAR LS_EMPLOYEE.

LS_EMPLOYEE-EMP_ID = '102'.
LS_EMPLOYEE-EMP_NAME = ' ROWDY'.
LS_EMPLOYEE-DEPARTMENT = 'SAP ABAP'.
LS_EMPLOYEE-MANAGER = 'KRISHNA'.
APPEND LS_EMPLOYEE TO LT_EMPLOYEE.
CLEAR LS_EMPLOYEE.

LS_EMPLOYEE-EMP_ID = '103'.
LS_EMPLOYEE-EMP_NAME = ' RAHULARUN'.
LS_EMPLOYEE-DEPARTMENT = 'SAP ABAP'.
LS_EMPLOYEE-MANAGER = 'KRISHNA'.
APPEND LS_EMPLOYEE TO LT_EMPLOYEE.
CLEAR LS_EMPLOYEE.

LS_EMPLOYEE-EMP_ID = '104'.
LS_EMPLOYEE-EMP_NAME = ' APPU'.
LS_EMPLOYEE-DEPARTMENT = 'SAP ABAP'.
LS_EMPLOYEE-MANAGER = 'KRISHNA'.
APPEND LS_EMPLOYEE TO LT_EMPLOYEE.
CLEAR LS_EMPLOYEE.

*DELETE LT_EMPLOYEE WHERE EMP_ID = '103'.

*DELETE LT_EMPLOYEE INDEX 3.

*LOOP AT LT_EMPLOYEE INTO LS_EMPLOYEE.
*  IF LS_EMPLOYEE-EMP_ID = '101'.
*    LS_EMPLOYEE-EMP_NAME = 'APPS'.
*MODIFY LT_EMPLOYEE FROM LS_EMPLOYEE.
*  ENDIF.
*ENDLOOP.

*READ TABLE LT_EMPLOYEE INTO LS_EMPLOYEE WITH KEY '101'.
*IF SY-SUBRC = 0.
*  WRITE:/ LS_EMPLOYEE-EMP_ID, LS_EMPLOYEE-EMP_NAME, LS_EMPLOYEE-DEPARTMENT, LS_EMPLOYEE-MANAGER.
*ENDIF.

*READ TABLE LT_EMPLOYEE INTO LS_EMPLOYEE INDEX 1.
*IF SY-SUBRC = 0.
*  WRITE:/ LS_EMPLOYEE-EMP_ID, LS_EMPLOYEE-EMP_NAME, LS_EMPLOYEE-DEPARTMENT, LS_EMPLOYEE-MANAGER.
*ENDIF.

*DATA : LV_COUNT TYPE I.
*DESCRIBE TABLE LT_EMPLOYEE LINES LV_COUNT.
*WRITE: / LV_COUNT.

SORT LT_EMPLOYEE BY EMP_ID.


LOOP AT LT_EMPLOYEE INTO LS_EMPLOYEE.
  WRITE:/ LS_EMPLOYEE-EMP_ID, LS_EMPLOYEE-EMP_NAME, LS_EMPLOYEE-DEPARTMENT, LS_EMPLOYEE-MANAGER.
ENDLOOP.